from pathlib import Path
from typing import Any

from ai_factory.agent_loader import load_agent_contract
from ai_factory.orchestrator import AGENT_ORDER
from ai_factory.state import load_state


MAX_ARTIFACT_CONTEXT_CHARS = 6000

UPSTREAM_ARTIFACT_PREFIXES = {
    "ux_ui": (
        "knowledge/project/",
        "workflows/backlog/",
    ),
    "architect": (
        "knowledge/project/",
        "workflows/backlog/",
        "design/ux-ui/",
    ),
    "developer": (
        "knowledge/project/",
        "workflows/backlog/",
        "design/ux-ui/",
        "knowledge/architecture/",
        "knowledge/decisions/",
    ),
    "qa": (
        "knowledge/project/requirements.md",
        "workflows/backlog/",
        "design/ux-ui/screen-specs.md",
        "knowledge/architecture/api.md",
    ),
    "security": (
        "knowledge/project/requirements.md",
        "knowledge/architecture/",
        "knowledge/decisions/",
    ),
    "devops": (
        "knowledge/architecture/",
        "knowledge/decisions/",
    ),
    "sre": (
        "knowledge/architecture/",
        "knowledge/decisions/",
    ),
}


def trim_artifact_content(
    content: str,
    max_chars: int = MAX_ARTIFACT_CONTEXT_CHARS,
) -> str:
    """Limit artifact content included in an agent execution context."""

    if len(content) <= max_chars:
        return content

    return (
        content[:max_chars].rstrip()
        + "\n\n[Artifact content truncated for execution context]"
    )


def is_artifact_relevant_to_agent(
    relative_path: str,
    agent_name: str,
) -> bool:
    """Return whether an upstream artifact is relevant to an agent."""

    prefixes = UPSTREAM_ARTIFACT_PREFIXES.get(
        agent_name
    )

    if prefixes is None:
        return True

    return any(
        relative_path.startswith(prefix)
        for prefix in prefixes
    )


def load_context_artifacts(
    project_root: Path,
    project_config: dict[str, Any],
    agent_name: str,
) -> dict[str, str]:
    """Load context artifacts configured for a specific agent."""

    context = project_config.get("context", {})
    agents_context = context.get("agents", {})

    artifact_paths = agents_context.get(
        agent_name,
        [],
    )

    if not isinstance(artifact_paths, list):
        raise ValueError(
            f"Context artifacts for agent '{agent_name}' must be a list."
        )

    artifacts: dict[str, str] = {}

    for relative_path in artifact_paths:
        artifact_path = project_root / relative_path

        if not artifact_path.exists():
            raise FileNotFoundError(
                f"Context artifact not found: {relative_path}"
            )

        artifacts[relative_path] = artifact_path.read_text(
            encoding="utf-8",
        )

    return artifacts


def load_agent_input(
    project_root: Path,
    project_config: dict[str, Any],
    agent_name: str,
) -> str | None:
    """Load optional human input for a specific agent."""

    inputs_config = project_config.get("inputs", {})

    if not isinstance(inputs_config, dict):
        raise ValueError(
            "Project inputs configuration must be a mapping."
        )

    input_directory = inputs_config.get(
        "directory",
        "knowledge/inputs",
    )

    if not isinstance(input_directory, str):
        raise ValueError(
            "Project input directory must be a string."
        )

    input_path = (
        project_root
        / input_directory
        / f"{agent_name}.md"
    )

    if not input_path.exists():
        return None

    return input_path.read_text(
        encoding="utf-8",
    )


def load_upstream_generated_artifacts(
    project_root: Path,
    state: dict[str, Any],
    agent_name: str,
) -> dict[str, str]:
    """Load artifacts generated by agents that precede the current agent."""

    try:
        current_index = AGENT_ORDER.index(agent_name)
    except ValueError as error:
        raise ValueError(
            f"Unknown agent in execution order: {agent_name}"
        ) from error

    agents = state.get("agents", {})

    artifacts: dict[str, str] = {}

    for upstream_agent in AGENT_ORDER[:current_index]:
        agent_state = agents.get(
            upstream_agent,
            {},
        )

        if not isinstance(agent_state, dict):
            continue

        last_result = agent_state.get(
            "last_result",
            {},
        )

        if not isinstance(last_result, dict):
            continue

        generated_paths = last_result.get(
            "generated_artifacts",
            [],
        )

        if not isinstance(generated_paths, list):
            continue

        for relative_path in generated_paths:
            if not is_artifact_relevant_to_agent(
                relative_path,
                agent_name,
            ):
                continue

            artifact_path = (
                project_root
                / relative_path
            )

            if not artifact_path.exists():
                raise FileNotFoundError(
                    f"Upstream artifact not found: {relative_path}"
                )

            content = artifact_path.read_text(
                encoding="utf-8",
            )

            artifacts[relative_path] = trim_artifact_content(
                content
            )

    return artifacts


def build_agent_context(
    project_root: Path,
    agent_name: str,
) -> dict[str, Any]:
    """Build the execution context required by an agent."""

    factory_dir = project_root / ".factory"

    state_path = factory_dir / "state.yaml"
    config_path = factory_dir / "project.yaml"

    state = load_state(state_path)
    project_config = load_state(config_path)
    contract = load_agent_contract(agent_name)

    artifacts = load_context_artifacts(
        project_root=project_root,
        project_config=project_config,
        agent_name=agent_name,
    )

    upstream_artifacts = load_upstream_generated_artifacts(
        project_root=project_root,
        state=state,
        agent_name=agent_name,
    )

    combined_artifacts = {
        **upstream_artifacts,
        **artifacts,
    }

    human_input = load_agent_input(
        project_root=project_root,
        project_config=project_config,
        agent_name=agent_name,
    )

    return {
        "agent_name": agent_name,
        "contract": contract,
        "project": project_config,
        "state": state,
        "artifacts": combined_artifacts,
        "human_input": human_input,
    }
